export enum NodeType {
  USER_INPUT = 'USER_INPUT',
  GATEKEEPER = 'GATEKEEPER', // The core principle
  EXPERT = 'EXPERT', // The agent
  CONCEPT = 'CONCEPT', // The analogy/idea generated by expert
  ROADMAP = 'ROADMAP' // Final synthesis
}

export interface NodeData {
  id: string;
  type: NodeType;
  label: string;
  content: string; // Full text content
  role?: string; // For experts (e.g., "Biologist")
  image?: string; // Base64 image for Concept nodes
  expanded?: boolean;
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
}

export interface LinkData {
  source: string | NodeData;
  target: string | NodeData;
}

export interface GraphState {
  nodes: NodeData[];
  links: LinkData[];
}

export interface AnalogyResult {
  title: string;
  explanation: string;
  imagePrompt: string;
}

export interface ExpertDefinition {
  id: string;
  role: string;
  color: string;
}

export const DEFAULT_EXPERTS: ExpertDefinition[] = [
  { id: 'exp-bio', role: 'Evolutionary Biologist', color: 'bg-green-600' },
  { id: 'exp-phys', role: 'Quantum Physicist', color: 'bg-purple-600' },
  { id: 'exp-hist', role: 'Historian', color: 'bg-amber-600' },
  { id: 'exp-eng', role: 'Mechanical Engineer', color: 'bg-blue-600' },
];